### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by zhangmhao** [xk/node-threads-a-gogo#54]
Getting this problem when trying to use on OSX 10.10.1  and Node.js 0.12.0

```
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@0.12.0 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrew/workspace/github/Life-Time-Tracker/node_modules/node-threads-a-gogo/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrew/.node-gyp/0.12.0/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/andrew/.node-gyp/0.12.0',
gyp info spawn args   '-Dmodule_root_dir=/Users/andrew/workspace/github/Life-Time-Tracker/node_modules/node-threads-a-gogo',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/threads_a_gogo/src/threads_a_gogo.o
../src/threads_a_gogo.cc:34:3: error: unknown type name 'uv_async_t'
  uv_async_t async_watcher; //MUST be the first one
  ^
../src/threads_a_gogo.cc:130:39: error: no member named 'GetPointerFromInternalField' in
      'v8::Object'
      thread= (typeThread*) receiver->GetPointerFromInternalField(0);
                            ~~~~~~~~  ^
../src/threads_a_gogo.cc:159:34: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
static Handle<Value> Puts (const Arguments &args) {
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/andrew/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
      declared here
class Arguments;
      ^
../src/threads_a_gogo.cc:162:15: error: calling a protected constructor of class
      'v8::HandleScope'
  HandleScope scope;
              ^
/Users/andrew/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/threads_a_gogo.cc:164:18: error: member access into incomplete type 'const
      v8::internal::Arguments'
  while (i < args.Length()) {
                 ^
/Users/andrew/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward declaration of
      'v8::internal::Arguments'
class Arguments;
      ^
../src/threads_a_gogo.cc:165:33: error: type 'const v8::internal::Arguments' does not
      provide a subscript operator
    String::Utf8Value c_str(args[i]);
                            ~~~~^~
../src/threads_a_gogo.cc:172:10: error: no matching function for call to 'Undefined'
  return Undefined();
         ^~~~~~~~~
/Users/andrew/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: candidate function not
      viable: requires single argument 'isolate', but no arguments were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../src/threads_a_gogo.cc:190:34: error: too few arguments to function call, expected 2, have
      1
  thread->isolate->SetData(thread);
  ~~~~~~~~~~~~~~~~~~~~~~~~       ^
/Users/andrew/.node-gyp/0.12.0/deps/v8/include/v8.h:6642:1: note: 'SetData' declared here
void Isolate::SetData(uint32_t slot, void* data) {
^
../src/threads_a_gogo.cc:220:40: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
static Handle<Value> threadEmit (const Arguments &args);
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/andrew/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
      declared here
class Arguments;
      ^
../src/threads_a_gogo.cc:224:33: error: too few arguments to function call, at least
      argument 'isolate' must be specified
  thread->context= Context::New();
                   ~~~~~~~~~~~~ ^
/Users/andrew/.node-gyp/0.12.0/deps/v8/include/v8.h:5263:3: note: 'New' declared here
  static Local<Context> New(
  ^
../src/threads_a_gogo.cc:225:18: error: member reference type 'Persistent<v8::Context>' is
      not a pointer; maybe you meant to use '.'?
  thread->context->Enter();
  ~~~~~~~~~~~~~~~^~
                 .
../src/threads_a_gogo.cc:225:20: error: no member named 'Enter' in
      'v8::Persistent<v8::Context, v8::NonCopyablePersistentTraits<v8::Context> >'
  thread->context->Enter();
  ~~~~~~~~~~~~~~~  ^
../src/threads_a_gogo.cc:228:17: error: calling a protected constructor of class
      'v8::HandleScope'
    HandleScope scope1;
                ^
/Users/andrew/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/threads_a_gogo.cc:230:42: error: member reference type 'Persistent<v8::Context>' is
      not a pointer; maybe you meant to use '.'?
    Local<Object> global= thread->context->Global();
                          ~~~~~~~~~~~~~~~^~
                                         .
../src/threads_a_gogo.cc:230:44: error: no member named 'Global' in
      'v8::Persistent<v8::Context, v8::NonCopyablePersistentTraits<v8::Context> >'
    Local<Object> global= thread->context->Global();
                          ~~~~~~~~~~~~~~~  ^
../src/threads_a_gogo.cc:231:25: error: no member named 'NewSymbol' in 'v8::String'
    global->Set(String::NewSymbol("puts"), FunctionTemplate::New(Puts)->GetFunction());
                ~~~~~~~~^
../src/threads_a_gogo.cc:232:45: error: too few arguments to function call, single argument
      'isolate' was not specified
    Local<Object> threadObject= Object::New();
                                ~~~~~~~~~~~ ^
/Users/andrew/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:3: note: 'New' declared here
  static Local<Object> New(Isolate* isolate);
  ^
../src/threads_a_gogo.cc:233:25: error: no member named 'NewSymbol' in 'v8::String'
    global->Set(String::NewSymbol("thread"), threadObject);
                ~~~~~~~~^
../src/threads_a_gogo.cc:235:31: error: no member named 'NewSymbol' in 'v8::String'
    threadObject->Set(String::NewSymbol("id"), Number::New(thread->id));
                      ~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/threads_a_gogo/src/threads_a_gogo.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/andrew/workspace/github/Life-Time-Tracker/node_modules/node-threads-a-gogo
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
```

Andrew

**Comment by TumboTheGnome** [comment]
I'm getting this error too.

**Comment by soultech67** [comment]
Me too - any fix on the horizon?

**Comment by dmitrif** [comment]
Same issue here.

**Comment by bmiller59** [comment]
+1

**Comment by looveu** [comment]
+1

**Comment by looveu** [comment]
Same issue node v0.12.7 and v4.2.1

**Comment by Jun90925** [comment]
Same issue here.

**Comment by ajeffrey** [comment]
same here on node v4.0.0

**Comment by gillsoft** [comment]
It is node and threads_a_gogo that doesn't work together at later node versions (e.g. threads_agogo needs to be installed from source to work). 

here are 5 steps to get it to work with the existing version:
1) uninstall node/npm
sudo rm -rf /usr/local/{lib/node{,/.npm,_modules},bin,share/man}/{npm*,node*,man1/node*}
2) Install nvm (in home folder)
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.1/install.sh | bash
3) close terminal and open a new one and write the following to activate nvm:
. ~/.nvm/nvm.sh
4) install node v0.10.41 (I didn't try any later versions except 4.1.1 that fails)
nvm install 0.10.41
5) go to your folder where your node project is and install
npm install threads_a_gogo --save

However, if you thought that would work out of the box, you're wrong!
Additional step:
In threads_a_gogo package.json change to "main": "build/Release/threads_a_gogo.node",
(e.g. Change to a capital R in Release) and save.

Now it will work :)

**Comment by CRAZYFAKE** [comment]
Same issue here.
Do you have a solution?

**Comment by ysyyork** [comment]
And updates? Same error here

**Comment by ysyyork** [comment]
FYI, I find this lib https://github.com/audreyt/node-webworker-threads which is a forked of this repo and provides all functions this repo provides.

**Comment by xk** [comment]
0.1.9 will fix that
