### ISSUE TITLE
Can't install TAGG from npm

### ISSUE THREAD

**Issue by blakewest** [xk/node-threads-a-gogo#60]
Hi,
Just trying to follow install instructions, and failing with `npm`. Here's the report. Note I'm using node version well above what the ReadMe says is required. I was doing this from within an existing project that has numerous other npm modules. Any thoughts would be appreciated! Would love to give this library a shot.
```sh
$ node --version
v6.7.0
$ node-gyp --version
v3.2.0
$ python --version
Python 2.7.9

$ npm install threads_a_gogo

> threads_a_gogo@0.1.9 install /Users/blakewest/code/UFC/js/node_modules/threads_a_gogo
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  ACTION *** THREADS_A_GOGO: RUN JS2C src/threads_a_gogo.cc
*** THREADS_A_GOGO: JS2C(kBoot_js): OK
*** THREADS_A_GOGO: JS2C(kPool_js): OK
  TOUCH Release/obj.target/configure.stamp
  CXX(target) Release/obj.target/threads_a_gogo/src/threads_a_gogo.o
../src/threads_a_gogo.cc:136:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> Puts (const Arguments &);
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/blakewest/.node-gyp/6.7.0/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/threads_a_gogo.cc:148:37: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> Destroy (const Arguments &);
                                    ^~~~~~~~~
                                    v8::internal::Arguments
/Users/blakewest/.node-gyp/6.7.0/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/threads_a_gogo.cc:149:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> Eval (const Arguments &);
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/blakewest/.node-gyp/6.7.0/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/threads_a_gogo.cc:150:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> Load (const Arguments &);
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/blakewest/.node-gyp/6.7.0/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/threads_a_gogo.cc:151:55: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static inline void pushEmitEvent (eventsQueue*, const Arguments &);
                                                      ^~~~~~~~~
                                                      v8::internal::Arguments
/Users/blakewest/.node-gyp/6.7.0/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/threads_a_gogo.cc:152:41: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> processEmit (const Arguments &);
                                        ^~~~~~~~~
                                        v8::internal::Arguments
/Users/blakewest/.node-gyp/6.7.0/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/threads_a_gogo.cc:153:40: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> threadEmit (const Arguments &);
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/blakewest/.node-gyp/6.7.0/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/threads_a_gogo.cc:154:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> Create (const Arguments &);
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/blakewest/.node-gyp/6.7.0/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/threads_a_gogo.cc:389:39: error: no member named 'GetPointerFromInternalField' in 'v8::Object'
      thread= (typeThread*) receiver->GetPointerFromInternalField(0);
                            ~~~~~~~~  ^
../src/threads_a_gogo.cc:436:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> Puts (const Arguments &args) {
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/blakewest/.node-gyp/6.7.0/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/threads_a_gogo.cc:438:18: error: member access into incomplete type 'const v8::internal::Arguments'
  while (i < args.Length()) {
                 ^
/Users/blakewest/.node-gyp/6.7.0/include/node/v8.h:147:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/threads_a_gogo.cc:439:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/blakewest/.node-gyp/6.7.0/include/node/v8.h:915:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/threads_a_gogo.cc:440:33: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    String::Utf8Value c_str(args[i]);
                            ~~~~^~
../src/threads_a_gogo.cc:445:10: error: no matching function for call to 'Undefined'
  return Undefined();
         ^~~~~~~~~
/Users/blakewest/.node-gyp/6.7.0/include/node/v8.h:324:27: note: candidate function not viable: requires single argument 'isolate', but no arguments were
      provided
  friend Local<Primitive> Undefined(Isolate* isolate);
                          ^
../src/threads_a_gogo.cc:467:33: error: too few arguments to function call, single argument 'params' was not specified
  thread->isolate= Isolate::New();
                   ~~~~~~~~~~~~ ^
/Users/blakewest/.node-gyp/6.7.0/include/node/v8.h:5650:3: note: 'New' declared here
  static Isolate* New(const CreateParams& params);
  ^
../src/threads_a_gogo.cc:468:34: error: too few arguments to function call, expected 2, have 1
  thread->isolate->SetData(thread);
  ~~~~~~~~~~~~~~~~~~~~~~~~       ^
/Users/blakewest/.node-gyp/6.7.0/include/node/v8.h:8568:1: note: 'SetData' declared here
void Isolate::SetData(uint32_t slot, void* data) {
^
../src/threads_a_gogo.cc:504:33: error: too few arguments to function call, at least argument 'isolate' must be specified
  thread->context= Context::New();
                   ~~~~~~~~~~~~ ^
/Users/blakewest/.node-gyp/6.7.0/include/node/v8.h:6982:3: note: 'New' declared here
  static Local<Context> New(
  ^
../src/threads_a_gogo.cc:505:18: error: member reference type 'Persistent<v8::Context>' is not a pointer; maybe you meant to use '.'?
  thread->context->Enter();
  ~~~~~~~~~~~~~~~^~
                 .
../src/threads_a_gogo.cc:505:20: error: no member named 'Enter' in 'v8::Persistent<v8::Context, v8::NonCopyablePersistentTraits<v8::Context> >'
  thread->context->Enter();
  ~~~~~~~~~~~~~~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/threads_a_gogo/src/threads_a_gogo.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/blakewest/.node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/6.7.0/bin/node" "/Users/blakewest/.node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/blakewest/code/UFC/js/node_modules/threads_a_gogo
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/6.7.0/bin/node" "/Users/blakewest/.node/bin/npm" "install" "threads_a_gogo"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! threads_a_gogo@0.1.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the threads_a_gogo@0.1.9 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the threads_a_gogo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs threads_a_gogo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls threads_a_gogo
npm ERR! There is likely additional logging output above.

```

**Comment by xk** [comment]
Sinceramente no tengo ni idea de cuando podré actualizarlo ni del tiempo que puede suponer. Mientras tanto por qué no lo pruebas con la v0.10.48 de node que va muy bien?

I honestly have no idea when I will be able to update it or the time it may take. In the meantime why don't you test it with node v0.10.48 that goes very well?

**Comment by xk** [comment]
La versión 0.1.13 funciona con todos los nodes hasta la v6.x.

Latest TAGG v0.1.13 works with all nodes up to v6.x.
