### ISSUE TITLE
node 8 not installed

### ISSUE THREAD

**Issue by darky** [xk/node-threads-a-gogo#67]

**Comment by finalclass** [comment]
Same here. node-threads-a-gogo does not install in node 8:
```
~/Documents/tmp (master *)$ nvm use 8
Now using node v8.4.0 (npm v5.5.1)
~/Documents/tmp (master *)$ npm install threads_a_gogo

> threads_a_gogo@0.1.13 install /home/sel/Documents/tmp/node_modules/threads_a_gogo
> node-gyp -v rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/home/sel/.nvm/versions/node/v8.4.0/bin/node',
gyp verb cli   '/home/sel/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   '-v',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.4.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb download using dist-url https://nodejs.org/dist
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.14\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.4.0
gyp verb command install [ '8.4.0' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb download using dist-url https://nodejs.org/dist
gyp verb install input version string "8.4.0"
gyp verb install installing version: 8.4.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.4.0
gyp verb build dir attempting to create "build" dir: /home/sel/Documents/tmp/node_modules/threads_a_gogo/build
gyp verb build dir "build" dir needed to be created? /home/sel/Documents/tmp/node_modules/threads_a_gogo/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/sel/Documents/tmp/node_modules/threads_a_gogo/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/sel/Documents/tmp/node_modules/threads_a_gogo/config.gypi
gyp verb common.gypi checking for gypi file: /home/sel/Documents/tmp/node_modules/threads_a_gogo/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/sel/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/sel/Documents/tmp/node_modules/threads_a_gogo/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/sel/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/sel/.node-gyp/8.4.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/sel/.node-gyp/8.4.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/sel/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/sel/.node-gyp/8.4.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/sel/Documents/tmp/node_modules/threads_a_gogo',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb download using dist-url https://nodejs.org/dist
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/sel/.node-gyp/8.4.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/sel/Documents/tmp/node_modules/threads_a_gogo/build'
  LD_LIBRARY_PATH=/home/sel/Documents/tmp/node_modules/threads_a_gogo/build/Release/lib.host:/home/sel/Documents/tmp/node_modules/threads_a_gogo/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; mkdir -p src; bash -c "cd /home/sel/Documents/tmp/node_modules/threads_a_gogo/src && node js2c.js"
*** THREADS_A_GOGO: JS2C(kBoot_js): OK
*** THREADS_A_GOGO: JS2C(kPool_js): OK
  touch Release/obj.target/configure.stamp
  g++ '-DNODE_GYP_MODULE_NAME=threads_a_gogo' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/sel/.node-gyp/8.4.0/include/node -I/home/sel/.node-gyp/8.4.0/src -I/home/sel/.node-gyp/8.4.0/deps/uv/include -I/home/sel/.node-gyp/8.4.0/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -pedantic -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -O3 -pedantic -MMD -MF ./Release/.deps/Release/obj.target/threads_a_gogo/src/threads_a_gogo.o.d.raw   -c -o Release/obj.target/threads_a_gogo/src/threads_a_gogo.o ../src/threads_a_gogo.cc
../src/threads_a_gogo.cc: In function ‘typeThread* isAThread(v8::Handle<v8::Object>)’:
../src/threads_a_gogo.cc:346:41: error: ‘class v8::Object’ has no member named ‘GetHiddenValue’; did you mean ‘IntegerValue’?
     v8::Local<v8::Value> ptr= receiver->GetHiddenValue(v8::String::NewFromUtf8(v8::Isolate::GetCurrent(), "ptr"));
                                         ^~~~~~~~~~~~~~
                                         IntegerValue
../src/threads_a_gogo.cc:347:54: warning: ‘v8::Local<v8::Number> v8::Value::ToNumber() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     thread= (typeThread*) ((uintptr_t) ptr->ToNumber()->Value());
                                                      ^
In file included from /home/sel/.node-gyp/8.4.0/include/node/node.h:63:0,
                 from ../src/threads_a_gogo.cc:4:
/home/sel/.node-gyp/8.4.0/include/node/v8.h:9578:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^~~~~
../src/threads_a_gogo.cc: In function ‘void eventLoop(typeThread*)’:
../src/threads_a_gogo.cc:520:72: warning: ‘v8::Local<v8::Value> v8::Object::CallAsFunction(v8::Local<v8::Value>, int, v8::Local<v8::Value>*)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Object> r= script->CallAsFunction(threadObject, 0, NULL)->ToObject();
                                                                        ^
In file included from /home/sel/.node-gyp/8.4.0/include/node/v8.h:26:0,
                 from /home/sel/.node-gyp/8.4.0/include/node/node.h:63,
                 from ../src/threads_a_gogo.cc:4:
/home/sel/.node-gyp/8.4.0/include/node/v8.h:3410:30: note: declared here
                 Local<Value> CallAsFunction(Local<Value> recv, int argc,
                              ^
/home/sel/.node-gyp/8.4.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/threads_a_gogo.cc:546:18: warning: ‘v8::TryCatch::TryCatch()’ is deprecated: Use isolate version [-Wdeprecated-declarations]
     v8::TryCatch onError;
                  ^~~~~~~
In file included from /home/sel/.node-gyp/8.4.0/include/node/v8.h:26:0,
                 from /home/sel/.node-gyp/8.4.0/include/node/node.h:63,
                 from ../src/threads_a_gogo.cc:4:
/home/sel/.node-gyp/8.4.0/include/node/v8.h:8157:40: note: declared here
   V8_DEPRECATED("Use isolate version", TryCatch());
                                        ^
/home/sel/.node-gyp/8.4.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/threads_a_gogo.cc:688:44: warning: ‘v8::Local<v8::Value> v8::Object::CallAsFunction(v8::Local<v8::Value>, int, v8::Local<v8::Value>*)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         dev->CallAsFunction(global, 2, args);
                                            ^
In file included from /home/sel/.node-gyp/8.4.0/include/node/v8.h:26:0,
                 from /home/sel/.node-gyp/8.4.0/include/node/node.h:63,
                 from ../src/threads_a_gogo.cc:4:
/home/sel/.node-gyp/8.4.0/include/node/v8.h:3410:30: note: declared here
                 Local<Value> CallAsFunction(Local<Value> recv, int argc,
                              ^
/home/sel/.node-gyp/8.4.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/threads_a_gogo.cc:701:46: warning: ‘v8::Local<v8::Value> v8::Object::CallAsFunction(v8::Local<v8::Value>, int, v8::Local<v8::Value>*)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     ntql= dnt->CallAsFunction(global, 0, NULL)->ToNumber()->Value();
                                              ^
In file included from /home/sel/.node-gyp/8.4.0/include/node/v8.h:26:0,
                 from /home/sel/.node-gyp/8.4.0/include/node/node.h:63,
                 from ../src/threads_a_gogo.cc:4:
/home/sel/.node-gyp/8.4.0/include/node/v8.h:3410:30: note: declared here
                 Local<Value> CallAsFunction(Local<Value> recv, int argc,
                              ^
/home/sel/.node-gyp/8.4.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/threads_a_gogo.cc:701:58: warning: ‘v8::Local<v8::Number> v8::Value::ToNumber() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     ntql= dnt->CallAsFunction(global, 0, NULL)->ToNumber()->Value();
                                                          ^
In file included from /home/sel/.node-gyp/8.4.0/include/node/node.h:63:0,
                 from ../src/threads_a_gogo.cc:4:
/home/sel/.node-gyp/8.4.0/include/node/v8.h:9578:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^~~~~
../src/threads_a_gogo.cc: In function ‘void cleanUpAfterThreadUVCallback(uv_handle_t*)’:
../src/threads_a_gogo.cc:790:101: warning: ‘v8::Local<v8::Value> v8::Object::CallAsFunction(v8::Local<v8::Value>, int, v8::Local<v8::Value>*)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     cb->ToObject()->CallAsFunction(v8::Isolate::GetCurrent()->GetCurrentContext()->Global(), 0, NULL);
                                                                                                     ^
In file included from /home/sel/.node-gyp/8.4.0/include/node/v8.h:26:0,
                 from /home/sel/.node-gyp/8.4.0/include/node/node.h:63,
                 from ../src/threads_a_gogo.cc:4:
/home/sel/.node-gyp/8.4.0/include/node/v8.h:3410:30: note: declared here
                 Local<Value> CallAsFunction(Local<Value> recv, int argc,
                              ^
/home/sel/.node-gyp/8.4.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/threads_a_gogo.cc: In function ‘void Callback(uv_async_t*)’:
../src/threads_a_gogo.cc:896:16: warning: ‘v8::TryCatch::TryCatch()’ is deprecated: Use isolate version [-Wdeprecated-declarations]
   v8::TryCatch onError;
                ^~~~~~~
In file included from /home/sel/.node-gyp/8.4.0/include/node/v8.h:26:0,
                 from /home/sel/.node-gyp/8.4.0/include/node/node.h:63,
                 from ../src/threads_a_gogo.cc:4:
/home/sel/.node-gyp/8.4.0/include/node/v8.h:8157:40: note: declared here
   V8_DEPRECATED("Use isolate version", TryCatch());
                                        ^
/home/sel/.node-gyp/8.4.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/threads_a_gogo.cc:922:63: warning: ‘v8::Local<v8::Value> v8::Object::CallAsFunction(v8::Local<v8::Value>, int, v8::Local<v8::Value>*)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       cb->ToObject()->CallAsFunction(that->ToObject(), 2, args);
                                                               ^
In file included from /home/sel/.node-gyp/8.4.0/include/node/v8.h:26:0,
                 from /home/sel/.node-gyp/8.4.0/include/node/node.h:63,
                 from ../src/threads_a_gogo.cc:4:
/home/sel/.node-gyp/8.4.0/include/node/v8.h:3410:30: note: declared here
                 Local<Value> CallAsFunction(Local<Value> recv, int argc,
                              ^
/home/sel/.node-gyp/8.4.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/threads_a_gogo.cc:928:37: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated: Use FatalException(isolate, ...) [-Wdeprecated-declarations]
         node::FatalException(onError);
                                     ^
In file included from ../src/threads_a_gogo.cc:4:0:
/home/sel/.node-gyp/8.4.0/include/node/node.h:339:29: note: declared here
                 inline void FatalException(const v8::TryCatch& try_catch) {
                             ^
/home/sel/.node-gyp/8.4.0/include/node/node.h:87:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
../src/threads_a_gogo.cc:950:81: warning: ‘v8::Local<v8::Value> v8::Object::CallAsFunction(v8::Local<v8::Value>, int, v8::Local<v8::Value>*)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       cb->ToObject()->CallAsFunction(iso->GetCurrentContext()->Global(), 2, args);
                                                                                 ^
In file included from /home/sel/.node-gyp/8.4.0/include/node/v8.h:26:0,
                 from /home/sel/.node-gyp/8.4.0/include/node/node.h:63,
                 from ../src/threads_a_gogo.cc:4:
/home/sel/.node-gyp/8.4.0/include/node/v8.h:3410:30: note: declared here
                 Local<Value> CallAsFunction(Local<Value> recv, int argc,
                              ^
/home/sel/.node-gyp/8.4.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/threads_a_gogo.cc: In function ‘void Destroy(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/threads_a_gogo.cc:1132:34: warning: ‘v8::Local<v8::Number> v8::Value::ToNumber() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     nuSigkill= args[0]->ToNumber()->Value() ? kKillRudely : kKillNicely;
                                  ^
In file included from /home/sel/.node-gyp/8.4.0/include/node/node.h:63:0,
                 from ../src/threads_a_gogo.cc:4:
/home/sel/.node-gyp/8.4.0/include/node/v8.h:9578:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^~~~~
../src/threads_a_gogo.cc: In function ‘void Create(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/threads_a_gogo.cc:1425:17: error: ‘class v8::Object’ has no member named ‘SetHiddenValue’; did you mean ‘IntegerValue’?
     nodeObject->SetHiddenValue(v8::String::NewFromUtf8(iso, "ptr"), v8::Number::New(iso, (double) ((uintptr_t) thread)));
                 ^~~~~~~~~~~~~~
                 IntegerValue
../src/threads_a_gogo.cc:1433:95: warning: ‘v8::Local<v8::Value> v8::Object::CallAsFunction(v8::Local<v8::Value>, int, v8::Local<v8::Value>*)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     thread->nodeDispatchEvents.Reset(iso, boot->ToObject()->CallAsFunction(nodeObject, 0, NULL)->ToObject());
                                                                                               ^
In file included from /home/sel/.node-gyp/8.4.0/include/node/v8.h:26:0,
                 from /home/sel/.node-gyp/8.4.0/include/node/node.h:63,
                 from ../src/threads_a_gogo.cc:4:
/home/sel/.node-gyp/8.4.0/include/node/v8.h:3410:30: note: declared here
                 Local<Value> CallAsFunction(Local<Value> recv, int argc,
                              ^
/home/sel/.node-gyp/8.4.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
make: *** [threads_a_gogo.target.mk:108: Release/obj.target/threads_a_gogo/src/threads_a_gogo.o] Error 1
make: Leaving directory '/home/sel/Documents/tmp/node_modules/threads_a_gogo/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/sel/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.13.8-1-ARCH
gyp ERR! command "/home/sel/.nvm/versions/node/v8.4.0/bin/node" "/home/sel/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "-v" "rebuild"
gyp ERR! cwd /home/sel/Documents/tmp/node_modules/threads_a_gogo
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/sel/Documents/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! threads_a_gogo@0.1.13 install: `node-gyp -v rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the threads_a_gogo@0.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sel/.npm/_logs/2017-10-31T17_14_42_091Z-debug.log

```

**Comment by xk** [comment]
This is a duplicate of issue #60 , in short:

THREADS_A_GOGO CURRENTLY (v0.1.13 / 2017)
RUNS ON NODES v0.5.1 TO v6.9.2
