### ISSUE TITLE
node v8.9.1 && npm v3.10.10 && v8 4.5 can't be installed

### ISSUE THREAD

**Issue by tekpig** [xk/node-threads-a-gogo#68]
threads_a_gogo.target.mk:108: recipe for target 'Release/obj.target/threads_a_gogo/src/threads_a_gogo.o' failed
make: *** [Release/obj.target/threads_a_gogo/src/threads_a_gogo.o] Error 1
make: Leaving directory '/home/ls/blockchain-explorer/node_modules/threads_a_gogo/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ls/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-62-generic
gyp ERR! command "/home/ls/node-v8.9.1-linux-x64/bin/node" "/home/ls/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "-v" "rebuild"
gyp ERR! cwd /home/ls/blockchain-explorer/node_modules/threads_a_gogo
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/home/ls/node-v8.9.1-linux-x64/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v8.9.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! threads_a_gogo@0.1.13 install: `node-gyp -v rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the threads_a_gogo@0.1.13 install script 'node-gyp -v rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the threads_a_gogo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp -v rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs threads_a_gogo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls threads_a_gogo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ls/blockchain-explorer/npm-debug.log

../src/threads_a_gogo.cc:346:41: error: ‘class v8::Object’ has no member named ‘GetHiddenValue’
     v8::Local<v8::Value> ptr= receiver->GetHiddenValue(v8::String::NewFromUtf8(v8::Isolate::GetCurrent(), "ptr"));

../src/threads_a_gogo.cc:1425:17: error: ‘class v8::Object’ has no member named ‘SetHiddenValue’
     nodeObject->SetHiddenValue(v8::String::NewFromUtf8(iso, "ptr"), v8::Number::New(iso, (double) ((uintptr_t) thread)));

**Comment by Jsnows** [comment]
Switching to a lower version of node can be used, such as v6.0.0, which is caused by the excessive version of the node-gyp version, or you can use the low version of the node-gyp rebuild for this project.
